### Create user : Success-code = 201

POST http://127.0.0.1:8000/auth/register/ HTTP/1.1
content-type: application/json

{
    "username":"cyrille1",
    "password":"calottedetesmorts"
}

### Get token : Success-code = 200
POST http://127.0.0.1:8000/auth/token/ HTTP/1.1
content-type: application/json

{
    "username":"cyrille1",
    "password":"calottedetesmorts"
}

### List user : Success-code = 200 (when authentification)
GET http://127.0.0.1:8000/auth/list HTTP/1.1
Authorization: Token f029bd845c0fc6f7fb5d51af45b7f7e6f623c695