### Create user : Success-code = 201

POST http://127.0.0.1:8000/auth/register/ HTTP/1.1
content-type: application/json

{
    "username":"b",
    "password":"b"
}

### Get token : Success-code = 200
POST http://127.0.0.1:8000/auth/token/ HTTP/1.1
content-type: application/json

{
    "username":"b",
    "password":"b"
}

### List user : Success-code = 200 (when authentification)
GET http://127.0.0.1:8000/auth/list HTTP/1.1
Authorization: Token 6e51b7c6e647a3dd2208e9f24f410905e86db979

### Bin List

GET http://127.0.0.1:8000/grabthetrash/list-garbage/ HTTP/1.1
Authorization: Token 7c22aa4563d989def8dc4127900ad63e46e931ce

### Add garbage : Success-code = 200
POST http://127.0.0.1:8000/grabthetrash/add-garbage/ HTTP/1.1
content-type: application/json
Authorization: Token 7c22aa4563d989def8dc4127900ad63e46e931ce

{
    "owner":"2",
    "latitude":"45",
    "longitude":"45"
}

### Add garbage : Success-code = 200
POST http://127.0.0.1:8000/grabthetrash/add-bin/ HTTP/1.1
content-type: application/json
Authorization: Token 7c22aa4563d989def8dc4127900ad63e46e931ce

{
    "owner":"2",
    "latitude":"45",
    "longitude":"45"
}

### Add bin

POST http://localhost:8000/grabthetrash/add-bin/ HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Token 88b880efa0177ffcadeb04e80b731730ee08c23a

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: application/json
Content-Disposition: form-data; name="owner"
{
    "owner":"2"
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: application/json
Content-Disposition: form-data; name="latitude"
{
    "latitude":"456465"
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="longitude"
"16545646"

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpg

< ./image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--