# Generated by Django 4.0.3 on 2022-04-30 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garbage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isRatingDone', models.BooleanField(default=False)),
                ('rate', models.IntegerField(null=True)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('image', models.ImageField(default='defaults.jpg', upload_to='garbage/', verbose_name='Image')),
                ('ratingJudge1', models.IntegerField(null=True)),
                ('ratingJudge2', models.IntegerField(null=True)),
                ('ratingJudge3', models.IntegerField(null=True)),
                ('judge1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='validator1', to=settings.AUTH_USER_MODEL)),
                ('judge2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='validator2', to=settings.AUTH_USER_MODEL)),
                ('judge3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='validator3', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isVerified', models.BooleanField(default=False)),
                ('isAccepted', models.BooleanField(null=True)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('image', models.ImageField(default='defaults.jpg', upload_to='bin/', verbose_name='Image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
