# Generated by Django 4.0.3 on 2022-06-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grabthetrash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='image',
        ),
        migrations.RemoveField(
            model_name='garbage',
            name='image',
        ),
    ]
