# Generated by Django 4.0.3 on 2022-06-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabthetrash', '0002_remove_bin_image_remove_garbage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bin',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='garbage',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='garbage',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
