# Generated by Django 4.0.3 on 2022-06-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabthetrash', '0003_alter_bin_latitude_alter_bin_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbage',
            name='judge3',
        ),
        migrations.RemoveField(
            model_name='garbage',
            name='ratingJudge3',
        ),
        migrations.AddField(
            model_name='garbage',
            name='discard',
            field=models.BooleanField(default=False),
        ),
    ]
